name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 깃허브 저장소 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v2

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # secrets 파일 생성
      - name: Create secrets.yml
        run: echo "${{ secrets.SECRETS_FILE }}" > src/main/resources/secrets.yml

      # Gradle 빌드
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      # SCP 활용 파일 전송
      - name: SCP to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "./build/libs/backend-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu"

      # SSH 활용 서버 실행
      - name: SSH to SERVERS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            JAR_PID=$(ps aux | grep backend-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print $2}')
              
            if [ ! -z "$JAR_PID" ]; then
              kill $JAR_PID
              echo "Killing process $JAR_PID"
            fi
            
            nohup java -jar build/libs/backend-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &

